version: "3"

services:

  db:
    image: postgres:13-alpine
    env_file:
      - .env/.local
    volumes:
      - db-volume:/var/lib/postgresql/data

  django:
    build:
      context: .
    container_name: survey_django
    ports:
      - "8000:8000"
    env_file:
      - .env/.local
    volumes:
      - .:/app
    command: bash -c "python project/manage.py migrate &&
             python project/manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db

volumes:
  db-volume:
