# Generated by Django 2.2.10 on 2021-11-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта'),
        ),
    ]
